baseURL = 'https://www.4jt.eu/'
theme = 'hugo-bearcub'
copyright = '4JT s.r.o.'
defaultContentlanguage = 'cs'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Your name. For more information on why this must be a list, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8
[author]
  name = "Petr Jezek"

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "4JT s.r.o."
    languageName = "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
     blogPath = "/home" # Path to your blog section (used by RSS)
     madeWith = ""
  [languages.cs]
    title = "Internet v ÃºdolÃ­ a na kopci"
    languageName = "cs ðŸ‡¨ðŸ‡¿"
    LanguageCode = "cs"
    contentDir = "content.cs"
    [languages.cs.params]
      blogPath = "/cs/home" # Path to your blog section (used by RSS)
      madeWith = "[Informace o zpracovanÃ­ osobnÃ­ch ÃºdajÅ¯ ](https://www.4jt.eu/podminky/informace/)"


[params]
  # The description of your website
  description = "Internet v ÃºdolÃ­ a na kopci"

	# The path to your favicon
  favicon = "images/favicon.png"

  # These images will show up when services want to generate a preview of a link
  # to your site. Ignored if `generateSocialCard = true`. For more information
  # about previews, see https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph
  images = ["/hugo-bearcub/images/share.webp"]
  
  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template  
	title = 'Internet v ÃºdolÃ­ a na kopci'

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = true
  
  disableKinds = ["RSS"]



  
# [social]
# email = 'info@4jt.eu'
